package stream

import (
	"bytes"
	"fmt"
	"strings"
	"testing"

	"github.com/cloakia/opencloak/internal/token"
)

// staticLookup builds a lookup closure over a fixed token→value table. Tokens
// absent from the table report found=false (the residual path).
func staticLookup(table map[string]string) func(string) (string, bool) {
	return func(tok string) (string, bool) {
		v, ok := table[tok]
		return v, ok
	}
}

// wholeRestore is the reference implementation: restore every token in the full
// buffer in one shot, with no holdback. The chunked Restorer must match this for
// any chunking of the same input.
func wholeRestore(table map[string]string, input string) string {
	return string(tokenRe.ReplaceAllFunc([]byte(input), func(m []byte) []byte {
		if restored, ok := token.RestoreKnownPrefix(string(m), staticLookup(table)); ok {
			return []byte(restored)
		}
		return m
	}))
}

// feedSplit feeds input to a fresh Restorer split at the given byte boundaries
// (each element is an absolute offset; the function writes [prev:off) slices),
// then flushes, and returns the concatenated output.
func feedSplit(table map[string]string, input string, splits []int) string {
	r := NewRestorer(staticLookup(table))
	var out bytes.Buffer
	prev := 0
	for _, off := range splits {
		out.Write(r.Write([]byte(input[prev:off])))
		prev = off
	}
	out.Write(r.Write([]byte(input[prev:])))
	out.Write(r.Flush())
	return out.String()
}

// ---- fixtures ----------------------------------------------------------------

// Hand-written tokens with 12+ hex ids (valid TokenPattern shape). Using real
// TYPE strings from internal/types keeps the residual TYPE accounting honest.
const (
	tokSecret = "OpenCloak_SECRET_0a1b2c3d4e5f"     // 12 hex
	tokEmail  = "OpenCloak_EMAIL_aabbccddeeff00"    // 12 hex
	tokIPv4   = "OpenCloak_IPV4_001122334455"       // 12 hex
	tokExtend = "OpenCloak_SECRET_0a1b2c3d4e5fabcd" // 16 hex (collision-extended)
)

var fixtureTable = map[string]string{
	tokSecret: "AKIAIOSFODNN7EXAMPLE",
	tokEmail:  "user@example.com",
	tokIPv4:   "10.0.0.1",
	tokExtend: "sk-live-extended-secret",
}

// ---- Test 1: equivalence property (the key gate) -----------------------------

// TestEquivalenceAllSplitBoundaries asserts that for several representative
// inputs, feeding the input as one chunk, split at EVERY byte boundary, and at a
// deterministic pseudo-random set of multi-byte boundaries, all yield output
// identical to the whole-buffer reference restore. This is the core guarantee:
// no token can leak when split across chunk boundaries.
func TestEquivalenceAllSplitBoundaries(t *testing.T) {
	inputs := []string{
		"prefix " + tokSecret + " middle " + tokEmail + " suffix",
		"no tokens here at all",
		tokSecret,                       // token is the entire input
		tokSecret + tokEmail,            // adjacent tokens, no separator
		"a" + tokIPv4 + "b" + tokExtend, // tight wrapping, extended id
		"trailing token at end " + tokEmail,
		"leading " + tokSecret + " then text",
		"OpenCloak_FOO_zzzzzzzzzzzz and " + tokSecret, // a non-hex OpenCloak-ish then a real token
		strings.Repeat(tokSecret+" ", 5),              // repeated tokens
	}

	for ti, input := range inputs {
		want := wholeRestore(fixtureTable, input)

		// 1a) single chunk.
		if got := feedSplit(fixtureTable, input, nil); got != want {
			t.Fatalf("input %d single-chunk mismatch:\n want %q\n got  %q", ti, want, got)
		}

		// 1b) split at every byte boundary 1..len-1.
		for cut := 1; cut < len(input); cut++ {
			if got := feedSplit(fixtureTable, input, []int{cut}); got != want {
				t.Fatalf("input %d split@%d mismatch:\n want %q\n got  %q", ti, cut, want, got)
			}
		}

		// 1c) split into single bytes (every boundary simultaneously).
		allBytes := make([]int, 0, len(input))
		for i := 1; i < len(input); i++ {
			allBytes = append(allBytes, i)
		}
		if got := feedSplit(fixtureTable, input, allBytes); got != want {
			t.Fatalf("input %d byte-by-byte mismatch:\n want %q\n got  %q", ti, want, got)
		}

		// 1d) deterministic pseudo-random multi-byte splits. The LCG is seeded by
		// a constant so the test is fully reproducible (no math/rand, no clock).
		for seed := uint32(1); seed <= 8; seed++ {
			splits := pseudoRandomSplits(len(input), seed)
			if got := feedSplit(fixtureTable, input, splits); got != want {
				t.Fatalf("input %d pseudo-random seed %d splits %v mismatch:\n want %q\n got  %q",
					ti, seed, splits, want, got)
			}
		}
	}
}

// pseudoRandomSplits returns a sorted, de-duplicated set of interior split
// offsets for a buffer of length n, generated by a deterministic LCG seeded by
// seed. Determinism is mandatory: the test must reproduce identically every run.
func pseudoRandomSplits(n int, seed uint32) []int {
	if n < 2 {
		return nil
	}
	state := seed
	next := func() uint32 {
		// Numerical Recipes LCG constants.
		state = state*1664525 + 1013904223
		return state
	}
	seen := make(map[int]struct{})
	var splits []int
	count := int(next()%uint32(n)) + 1
	for i := 0; i < count; i++ {
		off := int(next()%uint32(n-1)) + 1
		if _, ok := seen[off]; ok {
			continue
		}
		seen[off] = struct{}{}
		splits = append(splits, off)
	}
	// feedSplit requires ascending offsets.
	for i := 0; i < len(splits); i++ {
		for j := i + 1; j < len(splits); j++ {
			if splits[j] < splits[i] {
				splits[i], splits[j] = splits[j], splits[i]
			}
		}
	}
	return splits
}

// ---- Test 2: explicit mid-token / three-way splits ---------------------------

func TestSplitMidPrefix(t *testing.T) {
	input := "x " + tokSecret + " y"
	// Split right after "OpenCloak_" (mid-prefix, before TYPE).
	cut := strings.Index(input, tokSecret) + len("OpenCloak_")
	got := feedSplit(fixtureTable, input, []int{cut})
	want := "x AKIAIOSFODNN7EXAMPLE y"
	if got != want {
		t.Fatalf("mid-OpenCloak_ split: want %q got %q", want, got)
	}
}

func TestSplitMidHex(t *testing.T) {
	input := "x " + tokEmail + " y"
	// Split in the middle of the hex id.
	cut := strings.Index(input, tokEmail) + len("OpenCloak_EMAIL_") + 6
	got := feedSplit(fixtureTable, input, []int{cut})
	want := "x user@example.com y"
	if got != want {
		t.Fatalf("mid-hex split: want %q got %q", want, got)
	}
}

func TestThreeWaySplit(t *testing.T) {
	// "OpenCloak_SEC" | "RET_a1b2c3d4..." | tail — the token straddles three chunks.
	full := tokSecret
	a := "OpenCloak_SEC"
	rest := strings.TrimPrefix(full, a)
	// Split rest into a middle and a final byte so there are three writes total.
	b := rest[:len(rest)-1]
	c := rest[len(rest)-1:] + "!"

	r := NewRestorer(staticLookup(fixtureTable))
	var out bytes.Buffer
	out.Write(r.Write([]byte(a)))
	out.Write(r.Write([]byte(b)))
	out.Write(r.Write([]byte(c)))
	out.Write(r.Flush())

	want := "AKIAIOSFODNN7EXAMPLE!"
	if out.String() != want {
		t.Fatalf("three-way split: want %q got %q", want, out.String())
	}
}

// ---- Test 3: complete token mid-buffer, and token held to flush --------------

func TestCompleteTokenMidBufferRestoredImmediately(t *testing.T) {
	// A complete token followed by a non-hex byte is safe to restore on Write:
	// the following text proves the hex run terminated.
	input := tokSecret + " trailing text"
	r := NewRestorer(staticLookup(fixtureTable))
	out := r.Write([]byte(input))
	if !bytes.Contains(out, []byte("AKIAIOSFODNN7EXAMPLE")) {
		t.Fatalf("complete token mid-buffer not restored on Write: %q", out)
	}
	if bytes.Contains(out, []byte("OpenCloak_SECRET_")) {
		t.Fatalf("token still present after Write: %q", out)
	}
}

func TestTokenAtExactEndHeldUntilFlush(t *testing.T) {
	// A token at the very end of a chunk is extendable (more hex could follow),
	// so it must be held back until Flush proves termination.
	input := "value is " + tokEmail
	r := NewRestorer(staticLookup(fixtureTable))
	out := r.Write([]byte(input))
	if bytes.Contains(out, []byte("user@example.com")) {
		t.Fatalf("token at end should be held, not restored on Write: %q", out)
	}
	if bytes.Contains(out, []byte(tokEmail)) {
		t.Fatalf("token bytes should be held, not emitted on Write: %q", out)
	}
	flushed := r.Flush()
	full := string(out) + string(flushed)
	if full != "value is user@example.com" {
		t.Fatalf("after flush: want %q got %q", "value is user@example.com", full)
	}
}

// ---- Test 4: two tokens, second partial at boundary --------------------------

func TestTwoTokensSecondPartialAtBoundary(t *testing.T) {
	first := tokSecret
	second := tokEmail
	input := first + " gap " + second
	// Cut inside the second token's hex id.
	cut := strings.Index(input, second) + len("OpenCloak_EMAIL_") + 4
	r := NewRestorer(staticLookup(fixtureTable))
	var out bytes.Buffer
	w1 := r.Write([]byte(input[:cut]))
	// The first token must already be restored after the first Write; the second
	// is partial and held.
	if !bytes.Contains(w1, []byte("AKIAIOSFODNN7EXAMPLE")) {
		t.Fatalf("first token not restored in first Write: %q", w1)
	}
	if bytes.Contains(w1, []byte("user@example.com")) {
		t.Fatalf("second (partial) token leaked early: %q", w1)
	}
	out.Write(w1)
	out.Write(r.Write([]byte(input[cut:])))
	out.Write(r.Flush())
	want := "AKIAIOSFODNN7EXAMPLE gap user@example.com"
	if out.String() != want {
		t.Fatalf("two-token split: want %q got %q", want, out.String())
	}
}

// ---- Test 5: residual token (valid shape, unknown) ---------------------------

func TestResidualTokenEmittedAndCounted(t *testing.T) {
	// tokIPv4 is a valid token shape but we omit it from the lookup table.
	table := map[string]string{tokSecret: "AKIAIOSFODNN7EXAMPLE"}
	input := "known " + tokSecret + " unknown " + tokIPv4 + " end"
	r := NewRestorer(staticLookup(table))
	var out bytes.Buffer
	out.Write(r.Write([]byte(input)))
	out.Write(r.Flush())

	if bytes.Contains(out.Bytes(), []byte(tokSecret)) {
		t.Fatalf("known token not restored: %q", out.String())
	}
	if !bytes.Contains(out.Bytes(), []byte(tokIPv4)) {
		t.Fatalf("residual token should be emitted unchanged: %q", out.String())
	}
	counts := r.ResidualCounts()
	if counts["IPV4"] != 1 {
		t.Fatalf("expected residual IPV4 count 1, got %v", counts)
	}
	if counts["SECRET"] != 0 {
		t.Fatalf("restored token must not be counted as residual: %v", counts)
	}
}

func TestKnownTokenPrefixWithAdjacentHexSuffixRestores(t *testing.T) {
	const suffix = "0123456789abcdef0123456789abcdef"
	input := "value " + tokSecret + suffix + " done"
	want := "value AKIAIOSFODNN7EXAMPLE" + suffix + " done"

	for _, splits := range [][]int{
		nil,
		{len("value "+tokSecret) + 3},
		pseudoRandomSplits(len(input), 7),
	} {
		got := feedSplit(fixtureTable, input, splits)
		if got != want {
			t.Fatalf("splits %v:\n want %q\n got  %q", splits, want, got)
		}
	}
}

// ---- Test 6: non-token OpenCloak-ish strings pass through, not counted -------------

func TestNonTokenOpenCloakishUntouched(t *testing.T) {
	cases := []string{
		"OpenCloak_FOO_zzzzzzzzzzzz", // non-hex id
		"OpenCloak_BAR_0a1b",         // <12 hex
		"OpenCloaksomething",         // no separators
		"prefix OpenCloak_BAZ_ ",     // empty id then space
	}
	for _, input := range cases {
		r := NewRestorer(staticLookup(fixtureTable))
		var out bytes.Buffer
		out.Write(r.Write([]byte(input)))
		out.Write(r.Flush())
		if out.String() != input {
			t.Fatalf("non-token OpenCloak-ish string altered: input %q got %q", input, out.String())
		}
		if len(r.ResidualCounts()) != 0 {
			t.Fatalf("non-token OpenCloak-ish string counted as residual: %q -> %v", input, r.ResidualCounts())
		}
	}
}

// ---- Test 7: growth guard bounds the buffer ----------------------------------

// TestGrowthGuardBoundsBuffer feeds a long adversarial run of "OpenCloak_" + many 'A'
// (valid TYPE chars) that never completes into a token, across many Writes, and
// asserts the held-back buffer never exceeds MaxTokenLen after any Write. This
// is an in-package test so it can read the unexported buf field directly.
func TestGrowthGuardBoundsBuffer(t *testing.T) {
	r := NewRestorer(staticLookup(fixtureTable))
	chunk := []byte("OpenCloak_" + strings.Repeat("A", 500))
	for i := 0; i < 50; i++ {
		r.Write(chunk)
		if len(r.buf) > token.MaxTokenLen {
			t.Fatalf("buffer grew past MaxTokenLen (%d) after Write %d: len=%d",
				token.MaxTokenLen, i, len(r.buf))
		}
	}
	// And a single huge chunk in one Write.
	r2 := NewRestorer(staticLookup(fixtureTable))
	huge := []byte("text OpenCloak_" + strings.Repeat("A", 100000))
	r2.Write(huge)
	if len(r2.buf) > token.MaxTokenLen {
		t.Fatalf("buffer grew past MaxTokenLen (%d) after huge Write: len=%d",
			token.MaxTokenLen, len(r2.buf))
	}
}

// TestGrowthGuardDoesNotCorruptRealToken ensures the growth guard never splits a
// real, completable token: even when a huge non-completing run precedes a real
// token, the real token still restores correctly once it arrives.
func TestGrowthGuardDoesNotCorruptRealToken(t *testing.T) {
	r := NewRestorer(staticLookup(fixtureTable))
	var out bytes.Buffer
	// A long uncompletable run, then a real token, then text.
	out.Write(r.Write([]byte("OpenCloak_" + strings.Repeat("A", 1000))))
	out.Write(r.Write([]byte(" then " + tokSecret + " done")))
	out.Write(r.Flush())
	got := out.String()
	if !strings.Contains(got, "AKIAIOSFODNN7EXAMPLE") {
		t.Fatalf("real token after adversarial run not restored: %q", got)
	}
	// The adversarial run is emitted verbatim (it is not a token).
	if !strings.Contains(got, "OpenCloak_"+strings.Repeat("A", 1000)) {
		t.Fatalf("adversarial run was corrupted: %q", got[:60])
	}
}

// TestRealTokenAbuttingLongRun checks that a complete token directly followed by
// a long uppercase run (which terminates the token's hex id and is itself an
// uncompletable run) restores the token whole in a single Write — the trailing
// run neither extends the token nor causes the emitted region to bisect it.
func TestRealTokenAbuttingLongRun(t *testing.T) {
	// "text " then a real token then a long 'A' run with no completing id.
	input := "text " + tokSecret + strings.Repeat("A", 1000)
	r := NewRestorer(staticLookup(fixtureTable))
	var out bytes.Buffer
	out.Write(r.Write([]byte(input)))
	out.Write(r.Flush())
	got := out.String()
	// The real token's value must appear exactly once and intact.
	if !strings.Contains(got, "AKIAIOSFODNN7EXAMPLE") {
		t.Fatalf("real token at start of danger suffix not restored: %.80q", got)
	}
	if strings.Contains(got, "OpenCloak_SECRET_") {
		t.Fatalf("real token bytes leaked unrestored (possibly bisected): %.80q", got)
	}
	// Equivalence: same as whole-buffer restore.
	if want := wholeRestore(fixtureTable, input); got != want {
		t.Fatalf("guard altered output vs whole restore:\n want %.80q\n got  %.80q", want, got)
	}
}

// ---- ResidualCounts returns a copy ------------------------------------------

func TestResidualCountsReturnsCopy(t *testing.T) {
	table := map[string]string{}
	r := NewRestorer(staticLookup(table))
	r.Write([]byte(tokSecret + " "))
	r.Flush()
	c := r.ResidualCounts()
	c["SECRET"] = 999 // mutate the returned copy
	if r.ResidualCounts()["SECRET"] == 999 {
		t.Fatal("ResidualCounts must return a copy, not the internal map")
	}
}

// Example documents the basic relay shape for readers.
func ExampleRestorer() {
	table := map[string]string{"OpenCloak_EMAIL_aabbccddeeff00": "a@b.com"}
	r := NewRestorer(func(tok string) (string, bool) { v, ok := table[tok]; return v, ok })
	var out []byte
	out = append(out, r.Write([]byte("hello OpenCloak_EMAIL_aabb"))...)
	out = append(out, r.Write([]byte("ccddeeff00!"))...)
	out = append(out, r.Flush()...)
	fmt.Println(string(out))
	// Output: hello a@b.com!
}
