package proxy

import (
	"bytes"
	"io"
	"net/http"
	"strings"

	"github.com/tidwall/gjson"

	veil "github.com/PAIArtCom/Veil"
)

// SSE wire constants. Events are separated by a blank line; within an event,
// fields are "name: value" lines. Anthropic emits one data: line per event, but
// the spec permits multiple, which a conformant relay concatenates with "\n".
//
// Phase 0 frames on the LF blank line "\n\n", which is what Anthropic's
// /v1/messages stream emits (confirmed by the wire fixtures). The SSE spec also
// permits CRLF ("\r\n\r\n") and bare-CR separators; supporting those is deferred
// to Phase 1 alongside non-Anthropic providers.
const (
	sseEventSep = "\n\n"
	sseDataTag  = "data:"
	sseDoneData = "[DONE]"
)

// relayStream relays a Server-Sent Events response, driving the engine's
// stateful per-stream SSE restorer so a PAIArtVeil_ token regenerated by the model and
// split across multiple content_block_delta events (text or tool input) is
// reassembled and restored before it reaches the client (ADR-0011).
//
// Two layers of reassembly run together:
//
//   - Frame buffer (cross-TCP-read): bytes are appended as they arrive and only
//     COMPLETE events (terminated by a blank line) are split off and handed to
//     the restorer. A partial trailing event stays buffered until the bytes that
//     finish it arrive on a later read, so an event can never be processed
//     half-received (exit criterion #7).
//   - Stream restorer (cross-event holdback): the restorer holds per-content-
//     block state so a placeholder split across whole events is reassembled before any
//     match is attempted, and emits zero or more complete events per input event
//     (zero while buffering an input_json_delta; two when a held text tail or a
//     consolidated tool input flushes alongside a stop).
//
// The restorer is obtained BEFORE the response status/headers are committed: if
// it cannot be built (unsupported provider, invalid state) the stream is failed
// closed with a 502 rather than relayed with tokens unrestored.
func (p *Proxy) relayStream(w http.ResponseWriter, r *http.Request, resp *http.Response, state *veil.State, writeErr func(http.ResponseWriter, int, string, string)) {
	// Fail-closed: obtain the restorer before any byte of the response is
	// written. Once headers are sent a stream cannot be turned into an error
	// response, so a restorer failure must abort here. Relaying raw would leak
	// the very tokens this path exists to restore.
	sse, err := p.engine.NewSSEStreamRestorer(state)
	if err != nil {
		p.log.Error("proxy: build SSE stream restorer (fail-closed, not relayed)", "err", err)
		writeErr(w, http.StatusBadGateway, "upstream_error", "response could not be processed")
		return
	}

	// Copy headers and commit the status before the first flush. Content-Length
	// is meaningless for a stream and copyHeaders already drops it.
	copyHeaders(w.Header(), resp.Header)
	w.WriteHeader(resp.StatusCode)

	flusher, ok := w.(http.Flusher)
	if !ok {
		// No flushing available (should not happen with net/http's writer, but
		// guard rather than buffer an entire unbounded stream).
		p.log.Warn("proxy: response writer is not a Flusher; streaming without explicit flush")
	}

	var buf bytes.Buffer
	readBuf := make([]byte, 4096)

	for {
		n, readErr := resp.Body.Read(readBuf)
		if n > 0 {
			buf.Write(readBuf[:n])
			// Split off every complete event currently in the buffer.
			for {
				idx := bytes.Index(buf.Bytes(), []byte(sseEventSep))
				if idx < 0 {
					break // no complete event yet; keep buffering
				}
				event := make([]byte, idx)
				copy(event, buf.Bytes()[:idx])
				// Drop the event plus its separator from the buffer.
				buf.Next(idx + len(sseEventSep))

				if !p.relaySSEEvent(w, r, sse, event, flusher) {
					return
				}
			}
		}
		if readErr != nil {
			if readErr != io.EOF {
				// Mid-stream upstream read error: log and stop relaying. We do
				// not fabricate a tail event from a partial read.
				p.log.Error("proxy: upstream stream read error", "err", readErr)
				return
			}
			break
		}
	}

	// EOF: a well-formed Anthropic stream ends each event with a blank line, so
	// any final, unterminated buffered bytes are usually empty — but relay them
	// as a last event if present so a stream that closes without a trailing
	// separator still gets its last event restored rather than dropped.
	if buf.Len() > 0 {
		if !p.relaySSEEvent(w, r, sse, buf.Bytes(), flusher) {
			return
		}
	}

	// Drain any cross-event state still held by the restorer (e.g. a text tail
	// from a truncated stream, or a buffered tool input that never saw its
	// stop). A Flush error is logged, not fatal — the stream is already at EOF.
	outs, err := sse.Flush(r.Context())
	if err != nil {
		p.log.Error("proxy: flush SSE stream restorer", "err", err)
	}
	for _, payload := range outs {
		if !writeSSEPayload(w, payload) {
			p.log.Error("proxy: write flushed SSE payload to client")
			return
		}
	}
	if flusher != nil && len(outs) > 0 {
		flusher.Flush()
	}
}

// relaySSEEvent processes one complete SSE event block: it extracts the data:
// payload, drives the restorer, and writes the resulting payload(s) framed as
// SSE events. It returns false when a client write fails and relaying must stop.
//
// Blocks with no restorable data payload (comments, empty data, [DONE], or
// blocks with no data: line such as a bare event: keepalive) are passed through
// verbatim, preserving keepalive cadence. On a restorer error the ORIGINAL block
// is relayed unchanged and the error is logged — the stream is never dropped and
// the error is never swallowed (exit criterion #5).
func (p *Proxy) relaySSEEvent(w http.ResponseWriter, r *http.Request, sse sseRestorer, event []byte, flusher http.Flusher) bool {
	payload, ok := extractDataPayload(event)
	if !ok || len(payload) == 0 || string(payload) == sseDoneData {
		// Nothing to restore: relay the block verbatim.
		return writeRawEvent(w, event, flusher)
	}

	outs, err := sse.Event(r.Context(), payload)
	if err != nil {
		// Visible, not swallowed; original event relayed unchanged so the stream
		// continues and subsequent events (incl. message_stop) still arrive.
		p.log.Error("proxy: restore SSE event failed (relaying original event)", "err", err)
		return writeRawEvent(w, event, flusher)
	}

	for _, out := range outs {
		if !writeSSEPayload(w, out) {
			p.log.Error("proxy: write SSE event to client")
			return false
		}
	}
	if flusher != nil && len(outs) > 0 {
		flusher.Flush()
	}
	return true
}

// extractDataPayload returns the concatenated data: field value(s) of an SSE
// event block (multiple data: lines joined with "\n" per the SSE grammar) and
// whether any data: line was present. A single optional leading space after
// "data:" is stripped per the grammar; a trailing CR (CRLF framing) is trimmed
// per line. Non-data lines (event:, id:, retry:, comments) are ignored here —
// the restorer re-derives the event name from the payload's type field, which
// for Anthropic always equals the data.type.
func extractDataPayload(event []byte) (payload []byte, hasData bool) {
	var b strings.Builder
	for _, line := range strings.Split(string(event), "\n") {
		line = strings.TrimSuffix(line, "\r")
		if !strings.HasPrefix(line, sseDataTag) {
			continue
		}
		value := strings.TrimPrefix(line[len(sseDataTag):], " ")
		if hasData {
			b.WriteByte('\n')
		}
		b.WriteString(value)
		hasData = true
	}
	return []byte(b.String()), hasData
}

// writeSSEPayload frames one restored event payload as an SSE event and writes
// it. The event: name is derived from the payload's type field (Anthropic's
// event: line always equals data.type); a payload without a type still emits a
// valid data: event without an event: line. It returns false on a write error.
func writeSSEPayload(w http.ResponseWriter, payload []byte) bool {
	var frame bytes.Buffer
	if t := gjson.GetBytes(payload, "type").Str; t != "" {
		frame.WriteString("event: ")
		frame.WriteString(t)
		frame.WriteByte('\n')
	}
	frame.WriteString(sseDataTag)
	frame.WriteByte(' ')
	frame.Write(payload)
	frame.WriteString(sseEventSep)
	_, err := w.Write(frame.Bytes())
	return err == nil
}

// writeRawEvent relays an event block verbatim, re-appending the event
// separator that framing stripped. It returns false on a write error (the
// caller logs the higher-level relay failure).
func writeRawEvent(w http.ResponseWriter, event []byte, flusher http.Flusher) bool {
	if _, err := w.Write(event); err != nil {
		return false
	}
	if _, err := io.WriteString(w, sseEventSep); err != nil {
		return false
	}
	if flusher != nil {
		flusher.Flush()
	}
	return true
}
